use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Karen
Etheridge
ether
Randy
Stauner
rwstauner
Сергей
Романов
sromanov
lib
Dist
Zilla
MintingProfile
Author
ETHER
PluginBundle
Plugin
BlockRelease
